# -*- coding: utf-8 -*-
"""Micro_Project_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ce5F65UzDTIarXm3gJJbi6w0Rywmpahp
"""

# ==============================================================================
# PRO-TIER SUPPLY CHAIN OPTIMIZATION & INTERACTIVE MAPPING
# ==============================================================================
# Install required libraries silently
!pip install pulp folium -q

import pandas as pd
import pulp
import folium
from IPython.display import display, HTML

print("🚀 Initializing Optimization Engine...\n")

# ==========================================
# 1. DATA INGESTION & PROCESSING
# ==========================================
# Load files from the Colab current directory
facilities_df = pd.read_csv('facilities.csv')
demands_df = pd.read_csv('demands.csv')
warehouses_df = pd.read_csv('warehouses.csv')
transport_df = pd.read_csv('transportation_costs.csv')

# Merge facilities and demands to get all info in one place
fac_full_df = pd.merge(facilities_df, demands_df, on='facility_id')

# Define Project Scope based on Problem Statement
TARGET_FACILITIES = ['MED_CENTER', 'ENG_BUILDING', 'SCIENCE_HALL', 'DORM_A', 'DORM_B', 'LIBRARY']
TARGET_WAREHOUSES = ['WH_NORTH', 'WH_SOUTH', 'WH_EAST']
DAYS_IN_YEAR = 365
AMORT_YEARS = 10
BUDGET = 1500000

# Filter out the locations we don't need for Micro-Project 1
f_df = fac_full_df[fac_full_df['facility_id'].isin(TARGET_FACILITIES)].set_index('facility_id')
w_df = warehouses_df[warehouses_df['warehouse_id'].isin(TARGET_WAREHOUSES)].set_index('warehouse_id')

# Dictionary creations for optimization model
annual_demand = (f_df['daily_demand'] * DAYS_IN_YEAR).to_dict()
annual_capacity = (w_df['capacity'] * DAYS_IN_YEAR).to_dict()

# Calculate Annual Fixed Cost: (Construction Cost / 10 years) + (Daily Operational Cost * 365)
annual_fixed_cost = {}
for w_id, row in w_df.iterrows():
    annual_fixed_cost[w_id] = (row['construction_cost'] / AMORT_YEARS) + (row['operational_cost'] * DAYS_IN_YEAR)

# Create transport costs dictionary (Only for target locations)
trans_costs = {}
for _, row in transport_df.iterrows():
    if row['from_warehouse'] in TARGET_WAREHOUSES and row['to_facility'] in TARGET_FACILITIES:
        trans_costs[(row['from_warehouse'], row['to_facility'])] = row['cost_per_unit']

# ==========================================
# 2. MILP OPTIMIZATION MODEL (PuLP)
# ==========================================
# Create minimization problem
prob = pulp.LpProblem("Advanced_Campus_Logistics", pulp.LpMinimize)

# Decision Variables
# y[j]: Binary variable representing if warehouse is Open (1) or Closed (0)
y = pulp.LpVariable.dicts("Open_WH", TARGET_WAREHOUSES, cat='Binary')

# x[j][i]: Continuous variable for units shipped from warehouse j to facility i
x = pulp.LpVariable.dicts("Ship_Flow", (TARGET_WAREHOUSES, TARGET_FACILITIES), lowBound=0, cat='Continuous')

# Objective Function: Minimize Total Costs (Fixed + Transportation)
prob += pulp.lpSum(annual_fixed_cost[j] * y[j] for j in TARGET_WAREHOUSES) + \
        pulp.lpSum(trans_costs[(j, i)] * x[j][i] for j in TARGET_WAREHOUSES for i in TARGET_FACILITIES)

# Constraints
# 1. Satisfy Demand exactly for each facility
for i in TARGET_FACILITIES:
    prob += pulp.lpSum(x[j][i] for j in TARGET_WAREHOUSES) == annual_demand[i]

# 2. Warehouse capacity cannot be exceeded (and implies no shipping if y[j]=0)
for j in TARGET_WAREHOUSES:
    prob += pulp.lpSum(x[j][i] for i in TARGET_FACILITIES) <= annual_capacity[j] * y[j]

# 3. Select EXACTLY 2 Warehouses
prob += pulp.lpSum(y[j] for j in TARGET_WAREHOUSES) == 2

# 4. Strict Budget Limit
prob += pulp.lpSum(annual_fixed_cost[j] * y[j] for j in TARGET_WAREHOUSES) + \
        pulp.lpSum(trans_costs[(j, i)] * x[j][i] for j in TARGET_WAREHOUSES for i in TARGET_FACILITIES) <= BUDGET

# Solve the model
prob.solve()

# ==========================================
# 3. BUSINESS ANALYTICS & DASHBOARD
# ==========================================
if pulp.LpStatus[prob.status] != 'Optimal':
    print("❌ No optimal solution found. Please check constraints.")
else:
    total_cost = pulp.value(prob.objective)
    total_units = sum(annual_demand.values())
    cost_per_unit = total_cost / total_units

    print(f"✅ OPTIMIZATION SUCCESSFUL")
    print("-" * 50)
    print(f"💰 Total Annual Cost:     ${total_cost:,.2f}")
    print(f"📦 Total Units Delivered: {total_units:,.0f} units")
    print(f"📈 Avg. Cost Per Unit:    ${cost_per_unit:,.2f} / unit")
    print(f"🏦 Remaining Budget:      ${BUDGET - total_cost:,.2f}\n")

    # Generate visually appealing HTML tables for Colab Output
    wh_report = []
    for j in TARGET_WAREHOUSES:
        is_open = pulp.value(y[j]) > 0.5
        used_cap = sum(pulp.value(x[j][i]) for i in TARGET_FACILITIES) if is_open else 0
        wh_report.append({
            "Warehouse": j,
            "Status": "🟢 OPEN" if is_open else "🔴 CLOSED",
            "Fixed Cost": f"${annual_fixed_cost[j]:,.0f}",
            "Utilization": f"{(used_cap / annual_capacity[j]) * 100:.1f}%" if is_open else "0.0%"
        })

    routes_report = []
    for j in TARGET_WAREHOUSES:
        for i in TARGET_FACILITIES:
            units = pulp.value(x[j][i])
            if units > 0:
                routes_report.append({
                    "From": j, "To": i,
                    "Units Shipped": f"{units:,.0f}",
                    "Transport Cost": f"${units * trans_costs[(j, i)]:,.2f}"
                })

    display(HTML("<h3>🏢 Warehouse Utilization Report</h3>"))
    display(pd.DataFrame(wh_report).style.hide(axis="index"))

    display(HTML("<h3>🚚 Optimal Routing Schedule</h3>"))
    display(pd.DataFrame(routes_report).style.hide(axis="index"))

# ==========================================
# 4. INTERACTIVE GEOSPATIAL MAP (Folium)
# ==========================================
print("\n🗺️ Generating Interactive Map...")

# Center map on the average coordinates of our facilities
center_lat = f_df['latitude'].mean()
center_lon = f_df['longitude'].mean()
m = folium.Map(location=[center_lat, center_lon], zoom_start=14, tiles='CartoDB positron')

# Plot Facilities (Blue Markers)
for i, row in f_df.iterrows():
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        tooltip=f"<b>{row['facility_name']}</b><br>Demand: {annual_demand[i]:,.0f} units/yr",
        icon=folium.Icon(color="blue", icon="info-sign")
    ).add_to(m)

# Find max flow to scale line thickness dynamically
max_flow = max(pulp.value(x[j][i]) for j in TARGET_WAREHOUSES for i in TARGET_FACILITIES)

# Plot Warehouses and Flow Lines
for j, row in w_df.iterrows():
    is_open = pulp.value(y[j]) > 0.5
    lat, lon = row['latitude'], row['longitude']

    if is_open:
        used_cap = sum(pulp.value(x[j][i]) for i in TARGET_FACILITIES)
        util_pct = (used_cap / annual_capacity[j]) * 100
        popup_text = f"<b>{row['warehouse_name']}</b><br>Status: ACTIVE<br>Utilization: {util_pct:.1f}%"
        # Green star for active warehouses
        folium.Marker([lat, lon], tooltip=popup_text, icon=folium.Icon(color="green", icon="star")).add_to(m)

        # Draw flow lines from this warehouse to facilities
        for i in TARGET_FACILITIES:
            units = pulp.value(x[j][i])
            if units > 0:
                f_lat, f_lon = f_df.loc[i, 'latitude'], f_df.loc[i, 'longitude']
                weight = 2 + (units / max_flow) * 6 # Dynamic thickness
                folium.PolyLine(
                    locations=[[lat, lon], [f_lat, f_lon]],
                    color="green",
                    weight=weight,
                    opacity=0.6,
                    tooltip=f"<b>{j} ➔ {i}</b><br>Shipped: {units:,.0f} units"
                ).add_to(m)
    else:
        # Gray marker for closed warehouses
        folium.Marker([lat, lon], tooltip=f"{row['warehouse_name']} (CLOSED)", icon=folium.Icon(color="lightgray", icon="remove")).add_to(m)

# Display the map directly inline
display(m)